import {createGame,startGame,step,input,snapshot,MAX_PLAYERS,PARTS} from './runner-core.js?v=14';
export class Session{
 constructor(onChange,onMessage){this.onChange=onChange;this.onMessage=onMessage;this.mode='solo';this.id='solo';this.choice=null;this.skinIndex=4;this.loadouts=new Map();this.held=0;this.inputClock=0;this.game=createGame(['solo']);this.peers=new Map();this.members=['solo'];this.acc=0;this.sendClock=0;this.inputs=new Map();this.readiness=new Map();this.lastState=performance.now();this.closed=false;}
 notify(){this.onChange(this);}
 message(t){this.onMessage(t);}
 solo(){if(this.game.mode!=='lobby')this.choice=null;this.leave();this.mode='solo';this.id='solo';this.held=0;this.inputClock=0;this.members=['solo'];if(this.choice)this.loadouts.set(this.id,this.choice);this.game=this.lobbyGame();this.notify();}
 leave(){this.closed=true;clearTimeout(this.timeout);if(this.peer)this.peer.destroy();this.peer=null;this.peers.clear();this.closed=false;this.connection=null;this.inputs.clear();this.readiness.clear();this.loadouts.clear();}
 lobbyGame(){const g=createGame(this.members,Object.fromEntries(this.loadouts));if(this.mode==='solo'&&g.players[0])g.players[0].color=['#ed5365','#ff973f','#f6cf45','#50c889','#a344e0'][this.skinIndex];for(const p of g.players)p.ready=this.readiness.get(p.id)||false;return g;}
 equip(part){if(this.game.mode!=='lobby'||!Object.hasOwn(PARTS,part))return false;const own=this.game.players.find(p=>p.id===this.id);if(this.choice||own?.part||(this.mode==='guest'&&own?.ready))return false;this.choice=part;if(this.mode==='guest'){if(!this.connection?.open){this.choice=null;return false;}this.connection.send({type:'equip',part});}else{this.loadouts.set(this.id,part);if(own)own.part=part;this.broadcast();this.notify();}return true;}
 prepare(){if(!['solo','host'].includes(this.mode))return;this.choice=null;this.loadouts.clear();for(const id of this.members)this.readiness.set(id,id===this.id);this.game=this.lobbyGame();this.broadcast();this.notify();}
 async openPeer(id){if(!window.Peer)throw Error('접속 모듈을 불러오지 못했습니다.');const options={debug:0,...(window.RUNNER_PEER_OPTIONS||{})};return await new Promise((resolve,reject)=>{const peer=id?new Peer(id,options):new Peer(options);const timer=setTimeout(()=>{peer.destroy();reject(Error('접속 서버 응답이 없습니다. 혼자 플레이는 가능합니다.'));},15000);peer.once('open',()=>{clearTimeout(timer);resolve(peer);});peer.once('error',e=>{clearTimeout(timer);peer.destroy();reject(Error(e.type==='unavailable-id'?'방 코드가 이미 사용 중입니다. 다시 만드세요.':'접속 실패: '+e.type));});});}
 async host(){this.leave();this.mode='connecting';this.notify();const a=new Uint8Array(6);crypto.getRandomValues(a);this.code=Array.from(a,n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join('');try{this.peer=await this.openPeer('belcat-r14-'+this.code);this.id=this.peer.id;this.mode='host';this.members=[this.id];this.readiness.set(this.id,true);if(this.choice)this.loadouts.set(this.id,this.choice);this.game=this.lobbyGame();this.game.players[0].ready=true;this.peer.on('connection',c=>this.accept(c));this.peer.on('error',e=>this.message('접속 오류: '+e.type));this.notify();}catch(e){this.solo();this.message(e.message);}}
 accept(c){let accepted=false;const timeout=setTimeout(()=>{if(!accepted)c.close();},10000);c.on('open',()=>{clearTimeout(timeout);if(this.game.mode!=='lobby'||this.members.length>=MAX_PLAYERS||this.peers.has(c.peer)){c.send({type:'reject',reason:this.game.mode!=='lobby'?'이미 시작된 방입니다.':'정원 5명이 찼습니다.'});setTimeout(()=>c.close(),150);return;}accepted=true;this.peers.set(c.peer,c);this.members.push(c.peer);this.readiness.set(c.peer,false);this.game=this.lobbyGame();this.game.players.forEach(p=>p.ready=this.readiness.get(p.id)||false);c.send({type:'welcome',id:c.peer,code:this.code});this.broadcast();this.notify();});c.on('data',m=>{if(!accepted||!m||typeof m!=='object')return;if(m.type==='input'){input(this.game,c.peer,m.value);this.inputs.set(c.peer,performance.now());}if(m.type==='equip'){const p=this.game.players.find(p=>p.id===c.peer);if(this.game.mode==='lobby'&&p&&!p.ready&&!p.part&&Object.hasOwn(PARTS,m.part)){this.loadouts.set(c.peer,m.part);p.part=m.part;this.broadcast();this.notify();}else c.send({type:'equipRejected'});}if(m.type==='ready'&&this.game.mode==='lobby'){this.readiness.set(c.peer,!!m.value);this.game.players.find(p=>p.id===c.peer).ready=!!m.value;this.broadcast();this.notify();}if(m.type==='ping')c.send({type:'pong'});});const remove=()=>{clearTimeout(timeout);if(!accepted||this.peers.get(c.peer)!==c)return;accepted=false;this.peers.delete(c.peer);this.readiness.delete(c.peer);this.loadouts.delete(c.peer);this.members=this.members.filter(id=>id!==c.peer);this.game.players=this.game.players.filter(p=>p.id!==c.peer);if(this.game.mode==='lobby'){this.game=this.lobbyGame();this.game.players.forEach(p=>p.ready=this.readiness.get(p.id)||false);}this.broadcast();this.notify();this.message('참가자 한 명이 나갔습니다.');};c.on('close',remove);c.on('error',remove);}
 async join(code){code=code.trim().toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code)){this.message('6자리 방 코드를 입력하세요.');return;}this.leave();this.mode='connecting';this.notify();try{this.peer=await this.openPeer();this.id=this.peer.id;this.code=code;const c=this.peer.connect('belcat-r14-'+code,{reliable:true,serialization:'json'});this.connection=c;this.timeout=setTimeout(()=>{if(this.mode==='connecting'){this.leave();this.mode='error';this.notify();this.message('직접 연결에 실패했습니다. 방 코드와 네트워크를 확인하세요. 일부 통신망은 TURN 중계 서버가 필요합니다.');}},18000);c.on('data',m=>{if(m.type==='reject'){clearTimeout(this.timeout);this.mode='error';this.message(m.reason);this.notify();c.close();}else if(m.type==='welcome'){clearTimeout(this.timeout);this.mode='guest';this.lastState=performance.now();if(this.choice)c.send({type:'equip',part:this.choice});this.notify();}else if(m.type==='equipRejected'){this.choice=null;this.message('파츠 장착이 거절되었습니다. 준비 전 한 개만 선택할 수 있습니다.');this.notify();}else if(m.type==='state'){if(this.game.mode!=='lobby'&&m.game.mode==='lobby')this.choice=null;this.game=m.game;this.members=this.game.players.map(p=>p.id);this.lastState=performance.now();this.notify();}});c.on('open',()=>{this.message('연결됨 · 참가자 목록을 확인하세요.');});const lost=()=>{if(this.closed||this.mode==='error'||this.connection!==c)return;clearTimeout(this.timeout);this.mode='error';this.notify();this.message('방장 연결이 끊겼습니다. 혼자 시작하거나 새 방에 접속하세요.');};c.on('close',lost);c.on('error',lost);this.peer.on('error',e=>{this.message('접속 오류: '+e.type);});}catch(e){this.mode='error';this.message(e.message);this.notify();}}
 broadcast(){const msg={type:'state',game:snapshot(this.game)};for(const c of this.peers.values())if(c.open)c.send(msg);}
 ready(){if(this.mode==='guest'&&this.connection?.open)this.connection.send({type:'ready',value:true});}
 start(){if(this.game.mode!=='lobby')return;if(this.mode==='host'&&this.game.mode==='lobby'&&(this.members.length<2||this.game.players.some(p=>!p.ready))){this.message('참가자가 접속하고 준비 완료를 누르면 시작할 수 있습니다.');return;}if(this.mode==='solo'||this.mode==='host'){this.game=this.lobbyGame();startGame(this.game);this.broadcast();this.notify();}}
 steer(v){this.held=v;if(this.mode==='guest'){if(this.connection?.open)this.connection.send({type:'input',value:v});}else input(this.game,this.id,v);}
 pause(){if(this.mode==='guest')return;this.game.paused=!this.game.paused;this.broadcast();this.notify();}
 tick(dt){if(this.mode==='guest'){this.inputClock+=dt;if(this.inputClock>.2&&this.connection?.open){this.connection.send({type:'input',value:this.held});this.inputClock=0;}if(performance.now()-this.lastState>5000&&this.game.mode==='running'){if(!this.waitNotice||performance.now()-this.waitNotice>5000){this.waitNotice=performance.now();this.message('방장 응답 대기 중…');}}return;}if(!['solo','host'].includes(this.mode))return;for(const [id,stamp]of this.inputs)if(performance.now()-stamp>1500){input(this.game,id,0);this.inputs.delete(id);}this.acc+=Math.min(dt,.15);while(this.acc>=1/60){step(this.game,1/60);this.acc-=1/60;}this.sendClock+=dt;if(this.mode==='host'&&this.sendClock>=.05){this.sendClock=0;this.broadcast();} }
}
