import * as THREE from './vendor/three.module.js';
import {SURFACE,DEPTH,CAVE,COLORS,PLAYER_SCALE,windZones,smallWindmills,vortices,centre,position,rocks,gems,fallObstacles,boostZones,cats,progress,clamp} from './runner-core.js?v=13';
import {Session} from './runner-net.js?v=13';
const $=id=>document.getElementById(id);let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('error').style.display='grid';$('errorText').textContent='이 브라우저에서 WebGL을 사용할 수 없습니다.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;$('stage').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e6c894');scene.fog=new THREE.Fog('#e6c894',24,75);const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.08,180);
scene.add(new THREE.HemisphereLight(0xffedcf,0x452855,2));const sun=new THREE.DirectionalLight(0xffefd3,2.4);sun.position.set(-15,30,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=18;sun.shadow.camera.bottom=-18;sun.shadow.normalBias=.04;sun.shadow.camera.near=1;sun.shadow.camera.far=65;scene.add(sun);scene.add(sun.target);const caveLight=new THREE.PointLight(0xa58bff,160,35,2);scene.add(caveLight);
const surface=new THREE.Group(),shaft=new THREE.Group(),cave=new THREE.Group();scene.add(surface,shaft,cave);const cache=new Map();function mat(c){if(!cache.has(c))cache.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.62}));return cache.get(c);}const boxGeo=new THREE.BoxGeometry(1,1,1),ballGeo=new THREE.SphereGeometry(1,32,20),rockGeo=new THREE.IcosahedronGeometry(1,0),coneGeo=new THREE.ConeGeometry(1,1,12),gemGeo=new THREE.OctahedronGeometry(1,0),cylGeo=new THREE.CylinderGeometry(1,1,1,10),up=new THREE.Vector3(0,1,0),dummy=new THREE.Object3D();
function mesh(geo,m,parent){const o=new THREE.Mesh(geo,m);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function orb(parent,c,x,y,z,r){const o=mesh(ballGeo,mat(c),parent);o.position.set(x,y,z);o.scale.setScalar(r);return o;}
// A procedural studio environment supplies soft highlights without external assets.
const envFaces=Array.from({length:6},(_,i)=>{const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,128,128);g.addColorStop(0,'#514167');g.addColorStop(.35,i===2?'#ffffff':'#d1b9dc');g.addColorStop(.55,'#695173');g.addColorStop(1,'#30253e');x.fillStyle=g;x.fillRect(0,0,128,128);if(i===2||i===4){x.fillStyle='#fff7ef';x.fillRect(24,16,65,22);}return c;});const cube=new THREE.CubeTexture(envFaces);cube.needsUpdate=true;const pmrem=new THREE.PMREMGenerator(renderer);const studioEnv=pmrem.fromCubemap(cube).texture;pmrem.dispose();cube.dispose();
const sc=document.createElement('canvas');sc.width=sc.height=64;const sx=sc.getContext('2d'),sg=sx.createRadialGradient(32,32,2,32,32,32);sg.addColorStop(0,'rgba(56,26,71,.42)');sg.addColorStop(.55,'rgba(56,26,71,.22)');sg.addColorStop(1,'rgba(56,26,71,0)');sx.fillStyle=sg;sx.fillRect(0,0,64,64);const contactMap=new THREE.CanvasTexture(sc);
function makeCat(c){const g=new THREE.Group(),body=new THREE.Group();g.add(body);const head=orb(body,c,0,.62,0,.52);const gloss=new THREE.MeshPhysicalMaterial({color:new THREE.Color(c).multiplyScalar(.62),roughness:.34,metalness:0,clearcoat:.65,clearcoatRoughness:.2,envMap:studioEnv,envMapIntensity:.4});head.material=gloss;for(const x of[-.23,.23]){const ear=mesh(coneGeo,mat(c),body);ear.position.set(x,1.18,-.06);ear.scale.set(.17,.34,.17);ear.material=gloss;}orb(body,'#fff7ff',0,.56,.38,.20);orb(body,'#361453',0,.56,.54,.10);orb(body,'#ffffff',-.03,.60,.62,.025);const tail=[],joints=[];let parent=body;for(let i=0;i<4;i++){const joint=new THREE.Bone();joint.position.set(0,i===0?.31:-.04,i===0?-.54:-.23);parent.add(joint);const bead=orb(joint,c,0,0,0,.18-i*.02);bead.material=gloss;tail.push(bead);joints.push({bone:joint,angle:0,velocity:0});parent=joint;}const shadow=mesh(new THREE.PlaneGeometry(1.65,1.65),new THREE.MeshBasicMaterial({map:contactMap,transparent:true,depthWrite:false}),g);shadow.rotation.x=-Math.PI/2;shadow.position.y=.015;g.scale.setScalar(PLAYER_SCALE);shadow.castShadow=false;shadow.receiveShadow=false;shadow.visible=false;g.userData={body,head,tail,joints,shadow,pitch:0,pitchVelocity:0,lastContact:0};return g;}
// Ground has an actual hole at the end; purple edges follow the same centreline as players.
const shape=new THREE.Shape();for(let i=0;i<=SURFACE+35;i++){const z=i-20,x=centre(Math.max(0,Math.min(SURFACE,z)))-5;if(i===0)shape.moveTo(x,z);else shape.lineTo(x,z);}for(let i=SURFACE+35;i>=0;i--){const z=i-20;shape.lineTo(centre(Math.max(0,Math.min(SURFACE,z)))+5,z);}shape.closePath();const hole=new THREE.Path();hole.absarc(0,SURFACE,4.5,0,Math.PI*2,true);shape.holes.push(hole);const groundGeo=new THREE.ShapeGeometry(shape,64);groundGeo.rotateX(Math.PI/2);const ground=mesh(groundGeo,mat('#f2d29a'),surface);ground.material.side=THREE.DoubleSide;ground.castShadow=false;
const outer=new THREE.Shape();outer.moveTo(-90,-30);outer.lineTo(90,-30);outer.lineTo(90,SURFACE+40);outer.lineTo(-90,SURFACE+40);outer.closePath();const pit=new THREE.Path();pit.absarc(0,SURFACE,5,0,Math.PI*2,true);outer.holes.push(pit);const dg=new THREE.ShapeGeometry(outer,64);dg.rotateX(Math.PI/2);const desert=mesh(dg,mat('#cda77a'),surface);desert.position.y=-1.15;desert.material.side=THREE.DoubleSide;desert.castShadow=false;
function instanced(geo,color,count,parent){const m=new THREE.InstancedMesh(geo,mat(color),count);m.castShadow=false;m.receiveShadow=true;parent.add(m);return m;}
const railMat=mat('#b87de3');for(const side of[-1,1]){const points=Array.from({length:Math.ceil((SURFACE+40)/1.5)},(_,i)=>{const z=-16+i*1.5;return new THREE.Vector3(centre(Math.max(0,z))+side*5,.12,z);});const rail=mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),Math.ceil((SURFACE+40)*1.4),.13,6,false),railMat,surface);rail.castShadow=false;}
const lip=mesh(new THREE.TorusGeometry(4.5,.12,12,80),mat('#d1a0f0'),surface);lip.rotation.x=Math.PI/2;lip.position.set(0,.07,SURFACE);
const throat=mesh(new THREE.CylinderGeometry(4.5,4.5,1.3,64,1,true),mat('#9d60cf'),shaft);throat.material.side=THREE.BackSide;throat.position.set(0,-.65,SURFACE);throat.castShadow=false;throat.receiveShadow=false;throat.visible=false;
const shaftWall=mesh(new THREE.CylinderGeometry(4.5,5.3,DEPTH,40,1,true),mat('#3d205c'),shaft);shaftWall.material.side=THREE.BackSide;shaftWall.position.set(0,-DEPTH/2,SURFACE);shaftWall.castShadow=false;shaftWall.receiveShadow=false;
const wallColor=[];const wallPosition=shaftWall.geometry.attributes.position;for(let i=0;i<wallPosition.count;i++){const a=Math.atan2(wallPosition.getZ(i),wallPosition.getX(i)),c=new THREE.Color(['#554072','#3f315e','#685084'][Math.abs(Math.floor(a*9))%3]);wallColor.push(c.r,c.g,c.b);}shaftWall.geometry.setAttribute('color',new THREE.Float32BufferAttribute(wallColor,3));shaftWall.material=new THREE.MeshStandardMaterial({color:'#b5a1c5',vertexColors:true,side:THREE.BackSide,roughness:.9});
const shaftRocks=instanced(rockGeo,'#765296',50,shaft);for(let i=0;i<50;i++){const a=i*2.399;dummy.position.set(Math.cos(a)*4.35,-i/50*DEPTH,Math.sin(a)*4.35+SURFACE);dummy.rotation.set(i*.7,i,0);dummy.scale.setScalar(.25+(i%4)*.15);dummy.updateMatrix();shaftRocks.setMatrixAt(i,dummy.matrix);}
const curve=new THREE.CatmullRomCurve3(Array.from({length:65},(_,i)=>new THREE.Vector3(centre(i/64*CAVE,2),-DEPTH+3,SURFACE+i/64*CAVE)));const tunnel=mesh(new THREE.TubeGeometry(curve,390,5.8,11,false),mat('#705271'),cave);tunnel.material.side=THREE.BackSide;tunnel.castShadow=false;const caveFloor=mesh(new THREE.PlaneGeometry(35,CAVE+30),mat('#9a8ec0'),cave);caveFloor.rotation.x=-Math.PI/2;caveFloor.position.set(0,-DEPTH,SURFACE+CAVE/2);caveFloor.castShadow=false;
function xyz(s,lane,phase){return new THREE.Vector3(centre(s,phase)+lane*3,phase===2?-DEPTH:0,phase===2?SURFACE+s:s);}
const obstacles=new Map();for(const phase of[0,2]){const rr=rocks.filter(r=>r.phase===phase),rockMesh=instanced(rockGeo,phase===0?'#9c89ad':'#73608b',rr.length,phase===0?surface:cave);rr.forEach((r,i)=>{dummy.position.copy(xyz(r.s,r.lane,phase));dummy.position.y+=.45;dummy.rotation.set(.1,i,0);dummy.scale.set(.60,.6,.55);dummy.updateMatrix();rockMesh.setMatrixAt(i,dummy.matrix);});}
// Grouped leaves, low-poly rubble and glowing crystal clusters frame the playable lane.
for(const phase of[0,2]){const root=phase===0?surface:cave,green=instanced(phase===0?ballGeo:gemGeo,phase===0?'#6b9845':'#a86df4',450,root);if(phase===2){green.material=new THREE.MeshStandardMaterial({color:'#ad78ee',emissive:'#8056d2',emissiveIntensity:.55,roughness:.3});}for(let i=0;i<450;i++){const cluster=Math.floor(i/5),leaf=i%5,z=6+cluster*(phase===0?4.2:5.2),side=cluster%2?-1:1;dummy.position.copy(xyz(z,side*(phase===0?1.25:1.4),phase));dummy.position.x+=(leaf-2)*.18;dummy.position.z+=Math.sin(leaf*2)*.23;dummy.position.y+=.28+(leaf===2?.18:0);dummy.rotation.set(0,leaf*.7,side*(leaf-2)*.19);dummy.scale.set(phase===0?.22:.27,leaf===2?.68:.4,.23);dummy.updateMatrix();green.setMatrixAt(i,dummy.matrix);}}
const rubble=instanced(rockGeo,'#a994b3',300,surface);for(let i=0;i<300;i++){const z=i*1.43,side=i%2?-1:1;dummy.position.set(centre(z)+side*(3.65+(i%4)*.25),.12,z);dummy.rotation.set(i,.4*i,.2*i);dummy.scale.setScalar(.13+(i%3)*.07);dummy.updateMatrix();rubble.setMatrixAt(i,dummy.matrix);}
const backgroundRocks=instanced(rockGeo,'#b8957b',210,surface);for(let i=0;i<210;i++){const z=i*2.3-15;dummy.position.set(centre(z)+(i%2?-1:1)*(7+(i%5)*2),-.3,z);dummy.rotation.set(i,i*.8,0);dummy.scale.set(1+(i%3),.9+(i%5)*.4,1.4);dummy.updateMatrix();backgroundRocks.setMatrixAt(i,dummy.matrix);}
const cavernRocks=instanced(rockGeo,'#6b527d',480,cave);for(let i=0;i<480;i++){const z=(i>>1)*2.1,side=i%2?-1:1;dummy.position.copy(xyz(z,side*1.7,2));dummy.position.y+=.35+(i%4)*.45;dummy.rotation.set(i*.3,i*.7,.3);dummy.scale.set(.8+(i%3)*.25,.85+(i%4)*.3,1.2);dummy.updateMatrix();cavernRocks.setMatrixAt(i,dummy.matrix);}
const arches=instanced(rockGeo,'#805b66',270,cave);for(let i=0;i<270;i++){const arc=i%9,a=arc/8*Math.PI,z=6+Math.floor(i/9)*16;dummy.position.set(centre(z,2)+Math.cos(a)*5.45,-DEPTH+Math.sin(a)*5.6,SURFACE+z);dummy.rotation.set(0,i*.23,a);dummy.scale.set(.52,.52,.72);dummy.updateMatrix();arches.setMatrixAt(i,dummy.matrix);}
for(let i=0;i<34;i++){const z=8+i*14;const arch=mesh(new THREE.TorusGeometry(5.35,.48,7,20,Math.PI),mat('#735460'),cave);arch.position.set(centre(z,2),-DEPTH,SURFACE+z);arch.castShadow=false;}
const guideGeo=new THREE.BufferGeometry();guideGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.18,0,-.2,.18,0,-.2,0,0,.20],3));const guides=instanced(guideGeo,'#ddbc90',385,surface);guides.material=new THREE.MeshBasicMaterial({color:'#d7b98e',side:THREE.DoubleSide});guides.castShadow=guides.receiveShadow=false;for(let i=0;i<385;i++){const z=i+2;dummy.position.set(centre(z),.017,z);dummy.rotation.set(0,0,0);dummy.scale.setScalar(i%3===0?1:0);dummy.updateMatrix();guides.setMatrixAt(i,dummy.matrix);}
const caveGuides=instanced(guideGeo,'#cfcae8',470,cave);caveGuides.material=new THREE.MeshBasicMaterial({color:'#d1ccec',side:THREE.DoubleSide});caveGuides.castShadow=caveGuides.receiveShadow=false;for(let i=0;i<470;i++){dummy.position.copy(xyz(i+2,0,2));dummy.position.y+=.018;dummy.scale.setScalar(i%3===0?1:0);dummy.updateMatrix();caveGuides.setMatrixAt(i,dummy.matrix);}
const gemModels=new Map();for(const gem of gems){const m=mesh(gemGeo,new THREE.MeshBasicMaterial({color:'#ffd65e',toneMapped:false}),gem.phase===0?surface:cave);m.position.copy(xyz(gem.s,gem.lane,gem.phase));m.position.y+=.85;m.scale.set(.25,.40,.25);gemModels.set(gem.id,m);}
const catModels=cats.map(c=>{const g=makeCat('#9346c7');g.position.copy(xyz(c.s,c.lane,c.phase));(c.phase===0?surface:cave).add(g);return g;});
const torches=instanced(coneGeo,'#ffc266',72,cave);torches.material=new THREE.MeshBasicMaterial({color:'#ffc35b',toneMapped:false});torches.castShadow=false;for(let i=0;i<72;i++){dummy.position.copy(xyz(i*6.8,i%2?1.45:-1.45,2));dummy.position.y+=2.3;dummy.rotation.set(0,0,0);dummy.scale.set(.14,.50,.14);dummy.updateMatrix();torches.setMatrixAt(i,dummy.matrix);}const glowLight=new THREE.PointLight(0xffba58,170,33,2);scene.add(glowLight);
const boltCore=new THREE.MeshBasicMaterial({color:'#fff4ff',toneMapped:false}),boltPurple=new THREE.MeshBasicMaterial({color:'#be3ffc',transparent:true,opacity:.7,toneMapped:false,depthWrite:false});const shotModels=Array.from({length:35},()=>{const g=new THREE.Group();const core=mesh(cylGeo,boltCore,g),glow=mesh(cylGeo,boltPurple,g);core.scale.set(.065,1.7,.065);glow.scale.set(.16,2.1,.16);scene.add(g);g.visible=false;return g;});const effectModels=Array.from({length:25},()=>{const m=mesh(new THREE.TorusGeometry(1,.07,6,20),boltPurple,scene);m.castShadow=false;m.visible=false;return m;});
const streaks=instanced(cylGeo,'#ddd7ff',18,scene);streaks.material=new THREE.MeshBasicMaterial({color:'#e9dfff',transparent:true,opacity:.14,depthWrite:false,blending:THREE.AdditiveBlending});streaks.castShadow=streaks.receiveShadow=false;
const fallModels=fallObstacles.map(o=>{const g=new THREE.Group();const rock=mesh(rockGeo,mat('#b79acc'),g);rock.scale.set(o.width*3,.48,.95);g.position.set(o.lane*3,-o.depth,SURFACE);const band=mesh(new THREE.TorusGeometry(o.width*3,.05,6,24),new THREE.MeshBasicMaterial({color:'#e69dff'}),g);band.rotation.x=Math.PI/2;shaft.add(g);return g;});
const windmills=[];for(let i=0;i<12;i++){const z=22+i*31,side=i%2?1:-1,g=new THREE.Group();g.position.set(centre(z)+side*5.8,0,z);surface.add(g);g.traverse(o=>o.castShadow=false);const tower=mesh(new THREE.CylinderGeometry(.4,.8,3.8,10),mat('#f0dfbb'),g);tower.position.y=.75;const roof=mesh(coneGeo,mat('#9570b6'),g);roof.position.y=2.9;roof.scale.set(1,1.25,1);const rotor=new THREE.Group();rotor.position.set(0,1.95,-.6);g.add(rotor);orb(rotor,'#d2a1ea',0,0,0,.18);for(let j=0;j<4;j++){const arm=new THREE.Group();arm.rotation.z=j*Math.PI/2;rotor.add(arm);const blade=mesh(boxGeo,mat('#c59cde'),arm);blade.position.y=.9;blade.scale.set(.28,1.55,.10);}g.traverse(o=>o.castShadow=false);windmills.push(rotor);}
const miniRotors=smallWindmills.map(m=>{const g=new THREE.Group();g.position.copy(xyz(m.s,m.lane,m.phase));(m.phase===0?surface:cave).add(g);const tower=mesh(coneGeo,mat('#f2d5a5'),g);tower.position.y=.18;tower.scale.set(.15,.36,.15);const rotor=new THREE.Group();rotor.position.set(0,.4,-.08);g.add(rotor);orb(rotor,'#fbde93',0,0,0,.07);for(let j=0;j<4;j++){const arm=new THREE.Group();arm.rotation.z=j*Math.PI/2;rotor.add(arm);const blade=mesh(boxGeo,mat('#71cabe'),arm);blade.position.y=.12;blade.scale.set(.085,.24,.035);}g.traverse(o=>o.castShadow=false);return rotor;});
const vortexModels=vortices.map(v=>{const g=new THREE.Group();g.position.set(v.lane*3,-v.depth,SURFACE);shaft.add(g);for(let i=0;i<7;i++){const ring=mesh(new THREE.TorusGeometry(.25+i*.14,.035,5,32,Math.PI*1.65),new THREE.MeshBasicMaterial({color:'#b7fff5',transparent:true,opacity:.55,depthWrite:false}),g);ring.rotation.x=Math.PI/2;ring.position.y=(i-3)*.35;ring.castShadow=false;}return g;});
const windLines=Array.from({length:18},()=>{const m=mesh(cylGeo,new THREE.MeshBasicMaterial({color:'#effff8',transparent:true,opacity:.42,depthWrite:false}),scene);m.castShadow=m.receiveShadow=false;return m;});
const warningModels=cats.map(()=>{const m=mesh(cylGeo,new THREE.MeshBasicMaterial({color:'#ef7bff',transparent:true,opacity:.28,depthWrite:false}),scene);m.castShadow=false;return m;});
const boostMeshes=boostZones.map(z=>{const group=new THREE.Group();group.position.copy(xyz(z.s,z.lane,z.phase));group.position.y+=.025;(z.phase===0?surface:cave).add(group);const pad=mesh(new THREE.PlaneGeometry(2.8,2.8),new THREE.MeshBasicMaterial({color:'#55ded1',transparent:true,opacity:.42,depthWrite:false}),group);pad.rotation.x=-Math.PI/2;pad.castShadow=false;for(let i=0;i<3;i++){const arrow=mesh(guideGeo,new THREE.MeshBasicMaterial({color:'#d7fff7',side:THREE.DoubleSide}),group);arrow.position.set(0,.01,-.7+i*.7);arrow.scale.setScalar(2.2);arrow.castShadow=false;}return group;});
const models=new Map(),renderPositions=new Map();let firstPerson=false,viewSnap=true,toastTimer,lastFrame=performance.now(),fpsClock=0,frames=0,heading=new THREE.Vector3(0,0,1),lastPhase=-1,menuOpen=false,lookTarget=new THREE.Vector3();
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500);}
const session=new Session(updateUI,toast);
function updateUI(){const online=['host','guest'].includes(session.mode),lobby=session.game.mode==='lobby';$('room').hidden=!online;$('leave').hidden=!online&&session.mode!=='error';$('roomCode').textContent=session.code||'';$('members').textContent=`참가 ${session.members.length} / 5 · `+session.game.players.map(p=>p.name+(p.id===session.id?' (나)':'')+(session.game.mode==='lobby'?(p.ready?' ✓':' 대기'):'')).join(' · ');$('ready').hidden=session.mode!=='guest';$('ready').disabled=!!session.game.players.find(p=>p.id===session.id)?.ready;$('ready').textContent=$('ready').disabled?'준비 완료됨':'준비 완료';$('start').disabled=session.mode!=='host'||session.members.length<2||(session.game.mode==='lobby'&&session.game.players.some(p=>!p.ready));$('start').textContent=session.mode==='guest'?'방장 출발 대기':'함께 출발';$('host').disabled=session.mode==='connecting';$('join').disabled=session.mode==='connecting';$('solo').hidden=online;$('host').hidden=online;document.querySelector('.join').hidden=online;$('pause').disabled=session.mode==='guest';$('pause').textContent=session.game.paused?'▶':'Ⅱ';$('netStatus').textContent=session.mode==='connecting'?'접속 중…':online?`${session.code} · ${session.members.length}/5 · ${session.mode==='host'?'방장':'참가자'}`:session.mode==='error'?'연결 끊김':'혼자 플레이';if(session.game.mode==='running'&&!menuOpen)$('lobby').hidden=true;if(lobby||session.mode==='connecting'||session.mode==='error')$('lobby').hidden=false;const me=session.game.players.find(p=>p.id===session.id);if(me?.finished){$('results').hidden=false;$('again').disabled=session.mode==='guest';$('resultList').replaceChildren();for(const p of [...session.game.players].sort((a,b)=>(a.finishTime??Infinity)-(b.finishTime??Infinity))){const d=document.createElement('div');d.textContent=p.name+' · '+(p.finished?p.finishTime.toFixed(1)+'s':'이동 중')+' · 충돌 '+p.hits;$('resultList').append(d);}}}
$('ready').onclick=()=>session.ready();$('solo').onclick=()=>{session.solo();menuOpen=false;session.start();viewSnap=true;$('results').hidden=true;};$('host').onclick=()=>session.host();$('join').onclick=()=>session.join($('code').value);$('start').onclick=()=>{menuOpen=false;session.start();viewSnap=true;$('results').hidden=true;};$('leave').onclick=()=>{session.solo();menuOpen=false;$('lobby').hidden=false;};$('pause').onclick=()=>session.pause();$('again').onclick=()=>{session.start();$('results').hidden=true;viewSnap=true;};$('back').onclick=()=>{session.solo();$('results').hidden=true;$('lobby').hidden=false;};$('view').onclick=()=>{firstPerson=!firstPerson;$('view').textContent=firstPerson?'시점 · 1인칭':'시점 · 뒤에서';viewSnap=true;};$('menu').onclick=()=>{menuOpen=!menuOpen;$('lobby').hidden=!menuOpen;if(session.mode==='solo'&&session.game.mode==='running'){session.game.paused=menuOpen;updateUI();}};
$('share').onclick=async()=>{const text='벨켓 런 방 코드: '+session.code,url=new URL('./runner.html',location.href);url.searchParams.set('room',session.code);url.searchParams.set('v','13');try{if(navigator.share)await navigator.share({text,url:String(url)});else{await navigator.clipboard.writeText(text+'\n'+url);toast('방 코드와 링크를 복사했습니다.');}}catch(e){if(e.name!=='AbortError')toast('방 코드 '+session.code+'를 친구에게 알려 주세요.');}};
let steering=0,drag=null;function steer(v){steering=-v;session.steer(-v);}const joy=$('joystick'),knob=$('joyKnob');let joyPointer=null;function joyMove(e){const r=joy.getBoundingClientRect(),dx=clamp(e.clientX-r.left-r.width/2,-40,40),dy=clamp(e.clientY-r.top-r.height/2,-12,12);knob.style.transform=`translate(${dx}px,${dy}px)`;const value=Math.abs(dx)<4?0:(dx-Math.sign(dx)*4)/36;steer(value);joy.setAttribute('aria-valuenow',Math.round(value*100));}function joyRelease(){joyPointer=null;knob.style.transform='translate(0,0)';joy.setAttribute('aria-valuenow','0');steer(0);}joy.onpointerdown=e=>{if(joyPointer!==null)return;e.preventDefault();joyPointer=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e);};joy.onpointermove=e=>{if(joyPointer===e.pointerId)joyMove(e);};joy.onpointerup=joy.onpointercancel=e=>{if(joyPointer===e.pointerId)joyRelease();};joy.onlostpointercapture=()=>{if(joyPointer!==null)joyRelease();};joy.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();steer(e.key==='ArrowLeft'?-1:1);}};joy.onkeyup=joyRelease;addEventListener('blur',joyRelease);
renderer.domElement.onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX};renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(drag?.id===e.pointerId){steer(clamp((e.clientX-drag.x)/70,-1,1));}};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=()=>{drag=null;steer(0);};addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.key==='ArrowLeft'||e.key==='a')steer(-1);if(e.key==='ArrowRight'||e.key==='d')steer(1);});addEventListener('keyup',()=>steer(0));addEventListener('blur',()=>steer(0));document.addEventListener('visibilitychange',()=>{steer(0);if(document.hidden&&['solo','host'].includes(session.mode)&&session.game.mode==='running'){session.game.paused=true;session.broadcast();updateUI();}});
const initialRoom=new URLSearchParams(location.search).get('room');if(initialRoom){$('code').value=initialRoom;session.join(initialRoom);}
function render(dt,t){miniRotors.forEach((r,i)=>r.rotation.z=t*(3+i*.11));vortexModels.forEach((g,i)=>{g.rotation.y=t*(3+i);g.children.forEach((r,j)=>r.rotation.z=t*2+j*.8);});windmills.forEach((r,i)=>r.rotation.z=t*(.7+i*.04));const game=session.game,me=game.players.find(p=>p.id===session.id)||game.players[0],phase=me?.phase??0;surface.visible=phase===0||(phase===1&&me.fall<.24);cave.visible=phase>=2||(phase===1&&me.fall>.86);shaft.visible=phase<=1;scene.background.set(phase===0?'#d9b78a':'#443256');sun.intensity=phase===0?2.4:.55;caveLight.intensity=phase>=1?130:0;glowLight.intensity=phase>=1?125:0;scene.fog.color.copy(scene.background);scene.fog.near=phase===0?24:16;scene.fog.far=phase===0?75:48;const alive=new Set();for(const p of game.players){alive.add(p.id);if(!models.has(p.id)){const g=makeCat(p.color);scene.add(g);models.set(p.id,g);}const g=models.get(p.id),pos=position(p),target=new THREE.Vector3(pos.x,pos.y,pos.z),rp=renderPositions.get(p.id)||target.clone();rp.lerp(target,session.mode==='guest'&&p.id!==session.id?1-Math.exp(-dt*14):1);renderPositions.set(p.id,rp);g.position.copy(rp);g.userData.shadow.visible=false;g.visible=p.phase===phase&&!(p.id===session.id&&firstPerson);g.rotation.y=phase===1?0:Math.atan2(centre(p.s+1,p.phase)-centre(p.s,p.phase),1);g.userData.body.rotation.z=phase===1?Math.sin(t*4)*.1:-p.input*.15;const contact=game.effects.find(e=>['wall','hit','fallHit','bump','millHit'].includes(e.type)&&e.player===p.id);const squash=contact?Math.exp(-contact.age*14)*.22:0;g.userData.body.scale.set(1+squash,1-squash,1+squash*.4);g.userData.body.position.y=phase===1?0:Math.sin(t*13)*.035;const rig=g.userData,h=Math.min(dt,1/30);if(contact&&contact.id!==rig.lastContact){rig.lastContact=contact.id;rig.pitchVelocity+=(phase===1?-1:1)*2.2;rig.joints.forEach(j=>j.velocity+=p.vx*.55);}const pitchGoal=phase===1?Math.PI:0;rig.pitchVelocity+=((pitchGoal-rig.pitch)*160-rig.pitchVelocity*24)*h;rig.pitch+=rig.pitchVelocity*h;rig.body.rotation.x=rig.pitch;rig.joints.forEach((j,i)=>{const goal=clamp(-p.vx*.1+(i?rig.joints[i-1].angle*.45:rig.pitchVelocity*.025),-.4,.4);j.velocity+=((goal-j.angle)*65-j.velocity*12)*h;j.angle+=j.velocity*h;j.bone.rotation.y=j.angle;});}
for(const[id,g]of models)if(!alive.has(id)){scene.remove(g);models.delete(id);renderPositions.delete(id);}for(const gem of gems){const m=gemModels.get(gem.id);m.visible=!me?.gems.includes(gem.id);m.rotation.y=t*1.5;}
for(let i=0;i<cats.length;i++){const c=cats[i],g=catModels[i],recent=game.effects.find(e=>e.type==='fire'&&e.phase===c.phase&&Math.abs(e.s-c.s)<.1),kick=recent?Math.exp(-recent.age*12):0;const warning=game.warnings?.find(w=>w.cat===i);g.rotation.y=warning?Math.atan2(warning.vx,warning.vs):Math.atan2(-Math.sign(c.lane),0);g.userData.body.rotation.x=-kick*.5;g.userData.body.scale.set(1+kick*.25,1-kick*.15,1+kick*.25);}
warningModels.forEach((m,i)=>{const w=game.warnings?.find(w=>w.cat===i),c=cats[i];m.visible=!!w&&c.phase===phase;if(!m.visible)return;const dir=new THREE.Vector3(w.vx,0,w.vs).normalize();m.position.copy(xyz(c.s,c.lane,c.phase)).addScaledVector(dir,4.5);m.position.y+=.65;m.quaternion.setFromUnitVectors(up,dir);m.scale.set(.025,9,.025);});shotModels.forEach((g,i)=>{const q=game.shots[i];g.visible=!!q&&q.phase===phase;if(!g.visible)return;g.position.copy(xyz(q.s,q.x/3,q.phase));g.position.y+=.65;g.quaternion.setFromUnitVectors(up,new THREE.Vector3(q.vx,0,q.vs).normalize());});effectModels.forEach((m,i)=>{const e=game.effects[i];m.visible=!!e&&e.phase===phase&&e.type==='fire';if(!m.visible)return;m.position.copy(xyz(e.s,e.lane,e.phase));m.position.y+=.5;if(e.phase===1){m.position.y=-e.depth+.5;m.position.z=SURFACE;}m.scale.setScalar(.2+e.age*(e.type==='fire'?5:3));m.lookAt(camera.position);});
windLines.forEach((m,i)=>{m.visible=!!me?.wind&&phase!==1;if(!m.visible)return;const p=position(me),direction=Math.sign(me.wind);m.position.set(p.x+direction*((t*4+i*.7)%8-4),.3+(i%4)*.35,p.z+(i%6)*1.3-2);m.rotation.z=Math.PI/2;m.scale.set(.009,.6,.009);});streaks.visible=phase===1;if(me&&phase===1){const p=position(me);for(let i=0;i<18;i++){const a=i*2.4;dummy.position.set(p.x+Math.cos(a)*2.6,p.y+((t*16+i*3)%20)-9,p.z+Math.sin(a)*2.6);dummy.rotation.set(0,0,0);dummy.scale.set(.009,2+i%4,.009);dummy.updateMatrix();streaks.setMatrixAt(i,dummy.matrix);}}if(me){const rp=renderPositions.get(me.id),dir=new THREE.Vector3(centre(me.s+2,me.phase)-centre(me.s,me.phase),0,2).normalize();heading.lerp(dir,1-Math.exp(-dt*6));const anchor=firstPerson?rp.clone():new THREE.Vector3(phase===1?centre(SURFACE-3.5)*(1-me.fall):centre(me.s,phase>=2?2:0),rp.y,rp.z);const desired=anchor.clone(),look=anchor.clone();if(phase===1){desired.add(new THREE.Vector3(0,firstPerson?.8:10,-3.2));look.add(new THREE.Vector3(0,-4,1));if(!firstPerson){const blend=THREE.MathUtils.smoothstep(me.fall,0,.14);desired.lerp(anchor.clone().add(new THREE.Vector3(0,12,-8.4)),1-blend);look.lerp(anchor.clone().add(new THREE.Vector3(0,.1,7)),1-blend);}}else if(firstPerson){desired.y+=.72;desired.addScaledVector(heading,.42);look.addScaledVector(heading,12);look.y+=.8;}else{desired.addScaledVector(heading,phase>=2?-10:-8.4);desired.y+=phase>=2?4.35:12;look.addScaledVector(heading,phase>=2?8.5:7);look.y+=phase>=2?.9:.1;}lastPhase=phase;camera.position.lerp(desired,viewSnap?1:1-Math.exp(-dt*10));if(phase===1&&camera.position.y<-.3){const dx=camera.position.x,dz=camera.position.z-SURFACE,r=Math.hypot(dx,dz);if(r>4.1){camera.position.x=dx*4.1/r;camera.position.z=SURFACE+dz*4.1/r;}}lookTarget.lerp(look,viewSnap?1:1-Math.exp(-dt*12));camera.lookAt(lookTarget);viewSnap=false;sun.position.copy(anchor).add(new THREE.Vector3(-15,28,-5));sun.target.position.copy(anchor);caveLight.position.copy(anchor).add(phase===1?new THREE.Vector3(-1,7,-1):new THREE.Vector3(-2,3,6));glowLight.position.copy(anchor).add(new THREE.Vector3(3,2.5,14));$('phase').textContent=game.paused?'일시정지':phase===0?'지상 · 구멍을 향해':phase===1?(me.vortex?'회오리 · 낙하 감속':'수직 낙하'):phase===2?'지하 동굴':'도착';$('progress').style.height=progress(me)*170+'px';$('score').textContent=me.vortex?'회오리 · 낙하 속도 38%':me.wind?'횡풍 · '+(me.wind>0?'왼쪽':'오른쪽'):me.boost>0?'속도 ×1.5 · '+me.boost.toFixed(1)+'초':me.name+' · 충돌 '+me.hits;$('time').textContent=game.time.toFixed(1);}
renderer.clear(true,true,true);renderer.render(scene,camera);}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();renderer.compile(scene,camera);updateUI();
function frame(ts){const dt=Math.min((ts-lastFrame)/1000,.15);lastFrame=ts;session.tick(dt);render(dt,ts/1000);fpsClock+=dt;frames++;if(fpsClock>1){$('fps').textContent=Math.round(frames/fpsClock)+' FPS';fpsClock=0;frames=0;}if(session.game.mode==='finished'||session.game.players.find(p=>p.id===session.id)?.finished)updateUI();requestAnimationFrame(frame);}requestAnimationFrame(frame);window.runnerReady=true;window.runnerDiagnostics=()=>({mode:session.mode,id:session.id,code:session.code,players:session.game.players.map(p=>({...p})),phase:session.game.players.find(p=>p.id===session.id)?.phase,gameMode:session.game.mode,paused:session.game.paused,shots:session.game.shots.length,drawCalls:renderer.info.render.calls});
