import * as THREE from './vendor/three.module.js';
import {SURFACE,DEPTH,CAVE,COLORS,centre,position,rocks,gems,cats,progress,clamp} from './runner-core.js';
import {Session} from './runner-net.js';
const $=id=>document.getElementById(id);let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('error').style.display='grid';$('errorText').textContent='이 브라우저에서 WebGL을 사용할 수 없습니다.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('stage').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e6c894');scene.fog=new THREE.Fog('#e6c894',24,75);const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.08,180);
scene.add(new THREE.HemisphereLight(0xffedcf,0x452855,2));const sun=new THREE.DirectionalLight(0xffefd3,2.4);sun.position.set(-15,30,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-18;sun.shadow.camera.right=18;sun.shadow.camera.top=18;sun.shadow.camera.bottom=-18;sun.shadow.normalBias=.04;scene.add(sun);scene.add(sun.target);const caveLight=new THREE.PointLight(0xa58bff,75,27,2);scene.add(caveLight);
const surface=new THREE.Group(),shaft=new THREE.Group(),cave=new THREE.Group();scene.add(surface,shaft,cave);const cache=new Map();function mat(c){if(!cache.has(c))cache.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.62}));return cache.get(c);}const boxGeo=new THREE.BoxGeometry(1,1,1),ballGeo=new THREE.SphereGeometry(1,18,12),rockGeo=new THREE.IcosahedronGeometry(1,0),coneGeo=new THREE.ConeGeometry(1,1,12),gemGeo=new THREE.OctahedronGeometry(1,0),cylGeo=new THREE.CylinderGeometry(1,1,1,10),up=new THREE.Vector3(0,1,0),dummy=new THREE.Object3D();
function mesh(geo,m,parent){const o=new THREE.Mesh(geo,m);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function orb(parent,c,x,y,z,r){const o=mesh(ballGeo,mat(c),parent);o.position.set(x,y,z);o.scale.setScalar(r);return o;}
function makeCat(c){const g=new THREE.Group(),body=new THREE.Group();g.add(body);const head=orb(body,c,0,.55,0,.43);for(const x of[-.23,.23]){const ear=mesh(coneGeo,mat(c),body);ear.position.set(x,.98,.05);ear.scale.set(.14,.30,.14);}orb(body,'#fff7ff',0,.56,.38,.20);orb(body,'#361453',0,.56,.54,.10);orb(body,'#ffffff',-.03,.60,.62,.025);const tail=[];for(let i=0;i<4;i++)tail.push(orb(body,c,0,.28-i*.045,-.43-i*.19,.14-i*.018));g.userData={body,head,tail};return g;}
// Ground has an actual hole at the end; purple edges follow the same centreline as players.
const shape=new THREE.Shape();shape.moveTo(-38,-20);shape.lineTo(38,-20);shape.lineTo(38,SURFACE+25);shape.lineTo(-38,SURFACE+25);shape.closePath();const hole=new THREE.Path();hole.absarc(0,SURFACE,4.5,0,Math.PI*2,true);shape.holes.push(hole);const groundGeo=new THREE.ShapeGeometry(shape,64);groundGeo.rotateX(Math.PI/2);const ground=mesh(groundGeo,mat('#e8cb95'),surface);ground.material.side=THREE.DoubleSide;ground.castShadow=false;
function instanced(geo,color,count,parent){const m=new THREE.InstancedMesh(geo,mat(color),count);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
const rails=instanced(boxGeo,'#b37add',160,surface);for(let i=0;i<80;i++)for(let side=0;side<2;side++){const s=i*1.56,a=new THREE.Vector3(centre(s)+(side?4:-4),.18,s),b=new THREE.Vector3(centre(s+1.56)+(side?4:-4),.18,s+1.56),d=b.clone().sub(a);dummy.position.copy(a).add(b).multiplyScalar(.5);dummy.quaternion.setFromUnitVectors(up,d.normalize());dummy.scale.set(.18,1.63,.4);dummy.updateMatrix();rails.setMatrixAt(i*2+side,dummy.matrix);}const lip=mesh(new THREE.TorusGeometry(4.5,.16,8,64),mat('#b779e6'),surface);lip.rotation.x=Math.PI/2;lip.position.set(0,.10,SURFACE);
const shaftWall=mesh(new THREE.CylinderGeometry(4.5,5.3,DEPTH,40,1,true),mat('#3d205c'),shaft);shaftWall.material.side=THREE.BackSide;shaftWall.position.set(0,-DEPTH/2,SURFACE);shaftWall.castShadow=false;
const shaftRocks=instanced(rockGeo,'#765296',50,shaft);for(let i=0;i<50;i++){const a=i*2.399;dummy.position.set(Math.cos(a)*4.35,-i/50*DEPTH,Math.sin(a)*4.35+SURFACE);dummy.rotation.set(i*.7,i,0);dummy.scale.setScalar(.25+(i%4)*.15);dummy.updateMatrix();shaftRocks.setMatrixAt(i,dummy.matrix);}
const curve=new THREE.CatmullRomCurve3(Array.from({length:33},(_,i)=>new THREE.Vector3(centre(i/32*CAVE,2),-DEPTH+3,SURFACE+i/32*CAVE)));const tunnel=mesh(new THREE.TubeGeometry(curve,130,5.2,12,false),mat('#342045'),cave);tunnel.material.side=THREE.BackSide;tunnel.castShadow=false;const caveFloor=mesh(new THREE.PlaneGeometry(35,CAVE+30),mat('#877aab'),cave);caveFloor.rotation.x=-Math.PI/2;caveFloor.position.set(0,-DEPTH,SURFACE+CAVE/2);caveFloor.castShadow=false;
function xyz(s,lane,phase){return new THREE.Vector3(centre(s,phase)+lane*3,phase===2?-DEPTH:0,phase===2?SURFACE+s:s);}
const obstacles=new Map();for(const phase of[0,2]){const rr=rocks.filter(r=>r.phase===phase),rockMesh=instanced(rockGeo,phase===0?'#9c89ad':'#73608b',rr.length,phase===0?surface:cave);rr.forEach((r,i)=>{dummy.position.copy(xyz(r.s,r.lane,phase));dummy.position.y+=.45;dummy.rotation.set(.1,i,0);dummy.scale.set(.60,.6,.55);dummy.updateMatrix();rockMesh.setMatrixAt(i,dummy.matrix);});}
// Environment decoration uses instancing to keep phones from issuing hundreds of draw calls.
for(const phase of[0,2]){const root=phase===0?surface:cave,green=instanced(phase===0?ballGeo:gemGeo,phase===0?'#739c50':'#a761ef',75,root);for(let i=0;i<75;i++){const s=4+(i%25)*(phase===0?5:6),side=i%2?-1:1;dummy.position.copy(xyz(s,side*((phase===0?1.55:1.18)+(i%3)*.08),phase));dummy.position.y+=.25+(i%3)*.15;dummy.rotation.set(0,0,side*.25);dummy.scale.set(.18,.4+(i%3)*.12,.18);dummy.updateMatrix();green.setMatrixAt(i,dummy.matrix);}}
const gemModels=new Map();for(const gem of gems){const m=mesh(gemGeo,new THREE.MeshBasicMaterial({color:'#ffd65e',toneMapped:false}),gem.phase===0?surface:cave);m.position.copy(xyz(gem.s,gem.lane,gem.phase));m.position.y+=.85;m.scale.setScalar(.26);gemModels.set(gem.id,m);}
const catModels=cats.map(c=>{const g=makeCat('#9346c7');g.position.copy(xyz(c.s,c.lane,c.phase));(c.phase===0?surface:cave).add(g);return g;});
const torches=instanced(coneGeo,'#ffc266',24,cave);for(let i=0;i<24;i++){dummy.position.copy(xyz(i*6.8,i%2?1.5:-1.5,2));dummy.position.y+=2.7;dummy.rotation.set(0,0,0);dummy.scale.set(.14,.50,.14);dummy.updateMatrix();torches.setMatrixAt(i,dummy.matrix);}const glowLight=new THREE.PointLight(0xffba58,70,28,2);scene.add(glowLight);
const boltCore=new THREE.MeshBasicMaterial({color:'#fff4ff',toneMapped:false}),boltPurple=new THREE.MeshBasicMaterial({color:'#be3ffc',transparent:true,opacity:.7,toneMapped:false,depthWrite:false});const shotModels=Array.from({length:35},()=>{const g=new THREE.Group();const core=mesh(cylGeo,boltCore,g),glow=mesh(cylGeo,boltPurple,g);core.scale.set(.065,1.7,.065);glow.scale.set(.16,2.1,.16);scene.add(g);g.visible=false;return g;});const effectModels=Array.from({length:25},()=>{const m=mesh(new THREE.TorusGeometry(1,.07,6,20),boltPurple,scene);m.castShadow=false;m.visible=false;return m;});
const models=new Map(),renderPositions=new Map();let firstPerson=true,viewSnap=true,toastTimer,lastFrame=performance.now(),fpsClock=0,frames=0,heading=new THREE.Vector3(0,0,1),lastPhase=-1,menuOpen=false;
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500);}
const session=new Session(updateUI,toast);
function updateUI(){const online=['host','guest'].includes(session.mode),lobby=session.game.mode==='lobby';$('room').hidden=!online;$('leave').hidden=!online&&session.mode!=='error';$('roomCode').textContent=session.code||'';$('members').textContent=`참가 ${session.members.length} / 5 · `+session.game.players.map(p=>p.name+(p.id===session.id?' (나)':'')).join(' · ');$('start').disabled=session.mode!=='host';$('start').textContent=session.mode==='guest'?'방장 출발 대기':'함께 출발';$('host').disabled=session.mode==='connecting';$('join').disabled=session.mode==='connecting';$('solo').hidden=online;$('host').hidden=online;document.querySelector('.join').hidden=online;$('pause').disabled=session.mode==='guest';$('pause').textContent=session.game.paused?'▶':'Ⅱ';$('netStatus').textContent=session.mode==='connecting'?'접속 중…':online?`${session.code} · ${session.members.length}/5 · ${session.mode==='host'?'방장':'참가자'}`:session.mode==='error'?'연결 끊김':'혼자 플레이';if(session.game.mode==='running'&&!menuOpen)$('lobby').hidden=true;if(lobby||session.mode==='connecting'||session.mode==='error')$('lobby').hidden=false;const me=session.game.players.find(p=>p.id===session.id);if(me?.finished){$('results').hidden=false;$('again').disabled=session.mode==='guest';$('resultList').replaceChildren();for(const p of [...session.game.players].sort((a,b)=>(a.finishTime??Infinity)-(b.finishTime??Infinity))){const d=document.createElement('div');d.textContent=p.name+' · '+(p.finished?p.finishTime.toFixed(1)+'s':'이동 중')+' · ◆ '+p.score;$('resultList').append(d);}}}
$('solo').onclick=()=>{session.solo();menuOpen=false;session.start();viewSnap=true;$('results').hidden=true;};$('host').onclick=()=>session.host();$('join').onclick=()=>session.join($('code').value);$('start').onclick=()=>{menuOpen=false;session.start();viewSnap=true;$('results').hidden=true;};$('leave').onclick=()=>{session.solo();menuOpen=false;$('lobby').hidden=false;};$('pause').onclick=()=>session.pause();$('again').onclick=()=>{session.start();$('results').hidden=true;viewSnap=true;};$('back').onclick=()=>{session.solo();$('results').hidden=true;$('lobby').hidden=false;};$('view').onclick=()=>{firstPerson=!firstPerson;$('view').textContent=firstPerson?'시점 · 1인칭':'시점 · 뒤에서';viewSnap=true;};$('menu').onclick=()=>{menuOpen=!menuOpen;$('lobby').hidden=!menuOpen;if(session.mode==='solo'&&session.game.mode==='running'){session.game.paused=menuOpen;updateUI();}};
$('share').onclick=async()=>{const text='벨켓 런 방 코드: '+session.code,url=new URL('./runner.html',location.href);url.searchParams.set('room',session.code);try{if(navigator.share)await navigator.share({text,url:String(url)});else{await navigator.clipboard.writeText(text+'\n'+url);toast('방 코드와 링크를 복사했습니다.');}}catch(e){if(e.name!=='AbortError')toast('방 코드 '+session.code+'를 친구에게 알려 주세요.');}};
let steering=0,drag=null;function steer(v){steering=v;session.steer(v);}for(const[id,v]of[['left',-1],['right',1]]){const b=$(id);b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);steer(v);};b.onpointerup=b.onpointercancel=()=>steer(0);}renderer.domElement.onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX};renderer.domElement.setPointerCapture(e.pointerId);};renderer.domElement.onpointermove=e=>{if(drag?.id===e.pointerId){steer(clamp((e.clientX-drag.x)/70,-1,1));}};renderer.domElement.onpointerup=renderer.domElement.onpointercancel=()=>{drag=null;steer(0);};addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.key==='ArrowLeft'||e.key==='a')steer(-1);if(e.key==='ArrowRight'||e.key==='d')steer(1);});addEventListener('keyup',()=>steer(0));addEventListener('blur',()=>steer(0));document.addEventListener('visibilitychange',()=>{steer(0);if(document.hidden&&['solo','host'].includes(session.mode)&&session.game.mode==='running'){session.game.paused=true;session.broadcast();updateUI();}});
const initialRoom=new URLSearchParams(location.search).get('room');if(initialRoom)$('code').value=initialRoom;
function render(dt,t){const game=session.game,me=game.players.find(p=>p.id===session.id)||game.players[0],phase=me?.phase??0;surface.visible=phase===0;cave.visible=phase>=2;shaft.visible=phase<=1;scene.background.set(phase===0?'#e6c894':'#241132');scene.fog.color.copy(scene.background);scene.fog.near=phase===0?24:16;scene.fog.far=phase===0?75:48;const alive=new Set();for(const p of game.players){alive.add(p.id);if(!models.has(p.id)){const g=makeCat(p.color);scene.add(g);models.set(p.id,g);}const g=models.get(p.id),pos=position(p),target=new THREE.Vector3(pos.x,pos.y,pos.z),rp=renderPositions.get(p.id)||target.clone();rp.lerp(target,session.mode==='guest'?1-Math.exp(-dt*14):1);renderPositions.set(p.id,rp);g.position.copy(rp);g.visible=p.phase===phase&&!(p.id===session.id&&firstPerson);g.rotation.y=phase===1?0:Math.atan2(centre(p.s+1,p.phase)-centre(p.s,p.phase),1);g.userData.body.rotation.z=phase===1?Math.sin(t*4)*.1:-p.input*.15;g.userData.body.position.y=phase===1?0:Math.sin(t*13)*.035;g.userData.tail.forEach((o,i)=>o.position.x=Math.sin(t*8-i*.9)*.05);}
for(const[id,g]of models)if(!alive.has(id)){scene.remove(g);models.delete(id);renderPositions.delete(id);}for(const gem of gems){const m=gemModels.get(gem.id);m.visible=!me?.gems.includes(gem.id);m.rotation.y=t*1.5;}
for(let i=0;i<cats.length;i++){const c=cats[i],g=catModels[i],recent=game.effects.find(e=>e.type==='fire'&&e.phase===c.phase&&Math.abs(e.s-c.s)<.1),kick=recent?Math.exp(-recent.age*12):0;g.rotation.y=Math.atan2((me?.lane||0)-c.lane,(me?.s||0)-c.s);g.userData.body.rotation.x=-kick*.5;g.userData.body.scale.set(1+kick*.25,1-kick*.15,1+kick*.25);}
shotModels.forEach((g,i)=>{const q=game.shots[i];g.visible=!!q&&q.phase===phase;if(!g.visible)return;g.position.copy(xyz(q.s,q.x/3,q.phase));g.position.y+=.65;g.quaternion.setFromUnitVectors(up,new THREE.Vector3(q.vx,0,q.vs).normalize());});effectModels.forEach((m,i)=>{const e=game.effects[i];m.visible=!!e&&e.phase===phase;if(!m.visible)return;m.position.copy(xyz(e.s,e.lane,e.phase));m.position.y+=.5;m.scale.setScalar(.2+e.age*(e.type==='fire'?5:3));m.lookAt(camera.position);});
if(me){const rp=renderPositions.get(me.id),dir=new THREE.Vector3(centre(me.s+2,me.phase)-centre(me.s,me.phase),0,2).normalize();heading.lerp(dir,1-Math.exp(-dt*6));const desired=rp.clone(),look=rp.clone();if(phase===1){desired.add(new THREE.Vector3(0,firstPerson?.8:4,-2));look.add(new THREE.Vector3(0,-5,1));}else if(firstPerson){desired.y+=.72;desired.addScaledVector(heading,.42);look.addScaledVector(heading,12);look.y+=.8;}else{desired.addScaledVector(heading,-7.5);desired.y+=4.6;look.addScaledVector(heading,7);look.y+=.65;}if(phase!==lastPhase){viewSnap=true;lastPhase=phase;}camera.position.lerp(desired,viewSnap?1:1-Math.exp(-dt*10));camera.lookAt(look);viewSnap=false;sun.position.copy(rp).add(new THREE.Vector3(-15,28,-5));sun.target.position.copy(rp);caveLight.position.copy(rp).add(new THREE.Vector3(0,4,4));glowLight.position.copy(rp).add(new THREE.Vector3(3,3,12));$('phase').textContent=game.paused?'일시정지':phase===0?'지상 · 구멍을 향해':phase===1?'수직 낙하':phase===2?'지하 동굴':'도착';$('progress').style.height=progress(me)*170+'px';$('score').textContent='◆ '+me.score+' · '+me.name;$('time').textContent=game.time.toFixed(1);}
renderer.render(scene,camera);}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();updateUI();
function frame(ts){const dt=Math.min((ts-lastFrame)/1000,.15);lastFrame=ts;session.tick(dt);render(dt,ts/1000);fpsClock+=dt;frames++;if(fpsClock>1){$('fps').textContent=Math.round(frames/fpsClock)+' FPS';fpsClock=0;frames=0;}if(session.game.mode==='finished'||session.game.players.find(p=>p.id===session.id)?.finished)updateUI();requestAnimationFrame(frame);}requestAnimationFrame(frame);window.runnerReady=true;window.runnerDiagnostics=()=>({mode:session.mode,id:session.id,code:session.code,players:session.game.players.map(p=>({...p})),phase:session.game.players.find(p=>p.id===session.id)?.phase,gameMode:session.game.mode,paused:session.game.paused,shots:session.game.shots.length,drawCalls:renderer.info.render.calls});
